version: "3.7"

services:
  pci-frontend:
    container_name: pci-frontend
    image: piwatcher/pci-frontend:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_BASE_URL=http://cscap1.iot.nau.edu
    ports:
      - "4000:80"
