version: "3.7"

services:
  pci-frontend_dev:
    container_name: pci-frontend_dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    networks:
      - frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
